---
- name: download prometheus

- name: create prometheus groups
  groups:
    name: prometheus
    system: yes
    state: present
        
- name: create prometheus user
  user:
    name: prometheus
    system: yes
    shell: "/sbin/nologin"
    group: prometheus
    createhome: no

- name: install prometheus

